[build]
  command = "npm run build"
  publish = "dist"  # Vite uses 'dist' by default

[build.environment]
  NODE_VERSION = "18"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
