[build]
  command = "npm run build"
  publish = "out"  # Next.js defaults to 'out' for static exports

[build.environment]
  NODE_VERSION = "18"

# Skip puppeteer (not needed for static sites)
[context.production.environment]
  CI = "true"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA fallback (only needed if using client-side routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { Role = "!files", Path = "!/_next/static/*" }
